package com.oneler.entity.entity;

// Generated 2016-4-26 12:16:59 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GoodsrecipetId generated by hbm2java
 */
@Embeddable
public class GoodsrecipetId implements java.io.Serializable {

    private String goodsid;
    private String recipetid;
    private String unit;

    public GoodsrecipetId() {
    }

    public GoodsrecipetId(String goodsid, String recipetid, String unit) {
        this.goodsid = goodsid;
        this.recipetid = recipetid;
        this.unit = unit;
    }

    @Column(name = "GOODSID", nullable = false)
    public String getGoodsid() {
        return this.goodsid;
    }

    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

    @Column(name = "RECIPETID", nullable = false)
    public String getRecipetid() {
        return this.recipetid;
    }

    public void setRecipetid(String recipetid) {
        this.recipetid = recipetid;
    }

    @Column(name = "UNIT", nullable = false)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof GoodsrecipetId))
            return false;
        GoodsrecipetId castOther = (GoodsrecipetId) other;

        return ((this.getGoodsid() == castOther.getGoodsid()) || (this.getGoodsid() != null
                && castOther.getGoodsid() != null && this.getGoodsid().equals(castOther.getGoodsid())))
                && ((this.getRecipetid() == castOther.getRecipetid()) || (this.getRecipetid() != null
                        && castOther.getRecipetid() != null && this.getRecipetid().equals(castOther.getRecipetid())))
                && ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null && castOther.getUnit() != null
                        && this.getUnit().equals(castOther.getUnit())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getGoodsid() == null ? 0 : this.getGoodsid().hashCode());
        result = 37 * result + (getRecipetid() == null ? 0 : this.getRecipetid().hashCode());
        result = 37 * result + (getUnit() == null ? 0 : this.getUnit().hashCode());
        return result;
    }

}
