package com.oneler.entity.entity;

// Generated 2016-4-26 12:16:59 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Goodsrecipet generated by hbm2java
 */
@Entity
@Table(name = "goodsrecipet", catalog = "goods")
public class Goodsrecipet implements java.io.Serializable {

    private GoodsrecipetId id;
    private Goodst goodst;
    private Recipet recipet;

    public Goodsrecipet() {
    }

    public Goodsrecipet(GoodsrecipetId id, Goodst goodst, Recipet recipet) {
        this.id = id;
        this.goodst = goodst;
        this.recipet = recipet;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "goodsid", column = @Column(name = "GOODSID", nullable = false) ),
            @AttributeOverride(name = "recipetid", column = @Column(name = "RECIPETID", nullable = false) ),
            @AttributeOverride(name = "unit", column = @Column(name = "UNIT", nullable = false) ) })
    public GoodsrecipetId getId() {
        return this.id;
    }

    public void setId(GoodsrecipetId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GOODSID", nullable = false, insertable = false, updatable = false)
    public Goodst getGoodst() {
        return this.goodst;
    }

    public void setGoodst(Goodst goodst) {
        this.goodst = goodst;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECIPETID", nullable = false, insertable = false, updatable = false)
    public Recipet getRecipet() {
        return this.recipet;
    }

    public void setRecipet(Recipet recipet) {
        this.recipet = recipet;
    }

}
