package com.oneler.entity.entity;

// Generated 2016-4-26 12:16:59 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goodst generated by hbm2java
 */
@Entity
@Table(name = "goodst", catalog = "goods")
public class Goodst implements java.io.Serializable {

    private String goodstypeid;
    private String goodsid;
    private String goodsname;
    private String brandname;
    private String nname;
    private String lname;
    private String sname;
    private String fname;
    private String navid;
    private String ltypeid;
    private String stypeid;
    private Double price;
    private Double memberprice;
    private Double points;
    private String pictureurl;
    private Integer quantity;
    private String salestate;
    private String unitname;
    private String keywordname;
    private String weight;
    private Integer readcount;
    private String relatedproductid;
    private String recommended;
    private String hotsale;
    private String bargainprice;
    private Integer sort;
    private Date createtime;
    private String creatorid;
    private Integer replycount;
    private String brandid;
    private String placestore;
    private String metakeywords;
    private String metadescription;
    private Double cost;
    private Double saleprice;
    private String isnew;
    private String htmlpath;
    private String productsn;
    private String goodsparametervalue;
    private Integer freezestore;
    private String keywordid;
    private String unitnameid;
    private String goodstypename;
    private String usersetnum;
    private String isspecificationsopen;
    private Integer totalstar;
    private Integer totalstaruser;
    private Integer totalcomment;
    private String isvirtualsale;
    private String ismobileplatformgoods;
    private Integer sales;
    private Integer realsales;
    private Date updatetime;
    private Integer versiont;
    private String commoditylist;
    private String isoutsite;
    private String outsitelink;
    private String subgoodsname;
    private String shopid;
    private String shopname;
    private String isgroup;
    private String issecondkill;
    private Set<Goodsrecipet> goodsrecipets = new HashSet<Goodsrecipet>(0);

    public Goodst() {
    }

    public Goodst(String goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    public Goodst(String goodstypeid, String goodsid, String goodsname, String brandname, String nname, String lname,
            String sname, String fname, String navid, String ltypeid, String stypeid, Double price, Double memberprice,
            Double points, String pictureurl, Integer quantity, String salestate, String unitname, String keywordname,
            String weight, Integer readcount, String relatedproductid, String recommended, String hotsale,
            String bargainprice, Integer sort, Date createtime, String creatorid, Integer replycount, String brandid,
            String placestore, String metakeywords, String metadescription, Double cost, Double saleprice, String isnew,
            String htmlpath, String productsn, String goodsparametervalue, Integer freezestore, String keywordid,
            String unitnameid, String goodstypename, String usersetnum, String isspecificationsopen, Integer totalstar,
            Integer totalstaruser, Integer totalcomment, String isvirtualsale, String ismobileplatformgoods,
            Integer sales, Integer realsales, Date updatetime, Integer versiont, String commoditylist, String isoutsite,
            String outsitelink, String subgoodsname, String shopid, String shopname, String isgroup,
            String issecondkill, Set<Goodsrecipet> goodsrecipets) {
        this.goodstypeid = goodstypeid;
        this.goodsid = goodsid;
        this.goodsname = goodsname;
        this.brandname = brandname;
        this.nname = nname;
        this.lname = lname;
        this.sname = sname;
        this.fname = fname;
        this.navid = navid;
        this.ltypeid = ltypeid;
        this.stypeid = stypeid;
        this.price = price;
        this.memberprice = memberprice;
        this.points = points;
        this.pictureurl = pictureurl;
        this.quantity = quantity;
        this.salestate = salestate;
        this.unitname = unitname;
        this.keywordname = keywordname;
        this.weight = weight;
        this.readcount = readcount;
        this.relatedproductid = relatedproductid;
        this.recommended = recommended;
        this.hotsale = hotsale;
        this.bargainprice = bargainprice;
        this.sort = sort;
        this.createtime = createtime;
        this.creatorid = creatorid;
        this.replycount = replycount;
        this.brandid = brandid;
        this.placestore = placestore;
        this.metakeywords = metakeywords;
        this.metadescription = metadescription;
        this.cost = cost;
        this.saleprice = saleprice;
        this.isnew = isnew;
        this.htmlpath = htmlpath;
        this.productsn = productsn;
        this.goodsparametervalue = goodsparametervalue;
        this.freezestore = freezestore;
        this.keywordid = keywordid;
        this.unitnameid = unitnameid;
        this.goodstypename = goodstypename;
        this.usersetnum = usersetnum;
        this.isspecificationsopen = isspecificationsopen;
        this.totalstar = totalstar;
        this.totalstaruser = totalstaruser;
        this.totalcomment = totalcomment;
        this.isvirtualsale = isvirtualsale;
        this.ismobileplatformgoods = ismobileplatformgoods;
        this.sales = sales;
        this.realsales = realsales;
        this.updatetime = updatetime;
        this.versiont = versiont;
        this.commoditylist = commoditylist;
        this.isoutsite = isoutsite;
        this.outsitelink = outsitelink;
        this.subgoodsname = subgoodsname;
        this.shopid = shopid;
        this.shopname = shopname;
        this.isgroup = isgroup;
        this.issecondkill = issecondkill;
        this.goodsrecipets = goodsrecipets;
    }

    @Id

    @Column(name = "GOODSTYPEID", unique = true, nullable = false)
    public String getGoodstypeid() {
        return this.goodstypeid;
    }

    public void setGoodstypeid(String goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    @Column(name = "GOODSID")
    public String getGoodsid() {
        return this.goodsid;
    }

    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

    @Column(name = "GOODSNAME")
    public String getGoodsname() {
        return this.goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    @Column(name = "BRANDNAME")
    public String getBrandname() {
        return this.brandname;
    }

    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

    @Column(name = "NNAME")
    public String getNname() {
        return this.nname;
    }

    public void setNname(String nname) {
        this.nname = nname;
    }

    @Column(name = "LNAME")
    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    @Column(name = "SNAME")
    public String getSname() {
        return this.sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    @Column(name = "FNAME")
    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    @Column(name = "NAVID")
    public String getNavid() {
        return this.navid;
    }

    public void setNavid(String navid) {
        this.navid = navid;
    }

    @Column(name = "LTYPEID")
    public String getLtypeid() {
        return this.ltypeid;
    }

    public void setLtypeid(String ltypeid) {
        this.ltypeid = ltypeid;
    }

    @Column(name = "STYPEID")
    public String getStypeid() {
        return this.stypeid;
    }

    public void setStypeid(String stypeid) {
        this.stypeid = stypeid;
    }

    @Column(name = "PRICE", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "MEMBERPRICE", precision = 22, scale = 0)
    public Double getMemberprice() {
        return this.memberprice;
    }

    public void setMemberprice(Double memberprice) {
        this.memberprice = memberprice;
    }

    @Column(name = "POINTS", precision = 22, scale = 0)
    public Double getPoints() {
        return this.points;
    }

    public void setPoints(Double points) {
        this.points = points;
    }

    @Column(name = "PICTUREURL")
    public String getPictureurl() {
        return this.pictureurl;
    }

    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl;
    }

    @Column(name = "QUANTITY")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Column(name = "SALESTATE")
    public String getSalestate() {
        return this.salestate;
    }

    public void setSalestate(String salestate) {
        this.salestate = salestate;
    }

    @Column(name = "UNITNAME")
    public String getUnitname() {
        return this.unitname;
    }

    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    @Column(name = "KEYWORDNAME")
    public String getKeywordname() {
        return this.keywordname;
    }

    public void setKeywordname(String keywordname) {
        this.keywordname = keywordname;
    }

    @Column(name = "WEIGHT")
    public String getWeight() {
        return this.weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    @Column(name = "READCOUNT")
    public Integer getReadcount() {
        return this.readcount;
    }

    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    @Column(name = "RELATEDPRODUCTID")
    public String getRelatedproductid() {
        return this.relatedproductid;
    }

    public void setRelatedproductid(String relatedproductid) {
        this.relatedproductid = relatedproductid;
    }

    @Column(name = "RECOMMENDED")
    public String getRecommended() {
        return this.recommended;
    }

    public void setRecommended(String recommended) {
        this.recommended = recommended;
    }

    @Column(name = "HOTSALE")
    public String getHotsale() {
        return this.hotsale;
    }

    public void setHotsale(String hotsale) {
        this.hotsale = hotsale;
    }

    @Column(name = "BARGAINPRICE")
    public String getBargainprice() {
        return this.bargainprice;
    }

    public void setBargainprice(String bargainprice) {
        this.bargainprice = bargainprice;
    }

    @Column(name = "SORT")
    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 19)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "CREATORID")
    public String getCreatorid() {
        return this.creatorid;
    }

    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid;
    }

    @Column(name = "REPLYCOUNT")
    public Integer getReplycount() {
        return this.replycount;
    }

    public void setReplycount(Integer replycount) {
        this.replycount = replycount;
    }

    @Column(name = "BRANDID")
    public String getBrandid() {
        return this.brandid;
    }

    public void setBrandid(String brandid) {
        this.brandid = brandid;
    }

    @Column(name = "PLACESTORE")
    public String getPlacestore() {
        return this.placestore;
    }

    public void setPlacestore(String placestore) {
        this.placestore = placestore;
    }

    @Column(name = "METAKEYWORDS")
    public String getMetakeywords() {
        return this.metakeywords;
    }

    public void setMetakeywords(String metakeywords) {
        this.metakeywords = metakeywords;
    }

    @Column(name = "METADESCRIPTION")
    public String getMetadescription() {
        return this.metadescription;
    }

    public void setMetadescription(String metadescription) {
        this.metadescription = metadescription;
    }

    @Column(name = "COST", precision = 22, scale = 0)
    public Double getCost() {
        return this.cost;
    }

    public void setCost(Double cost) {
        this.cost = cost;
    }

    @Column(name = "SALEPRICE", precision = 22, scale = 0)
    public Double getSaleprice() {
        return this.saleprice;
    }

    public void setSaleprice(Double saleprice) {
        this.saleprice = saleprice;
    }

    @Column(name = "ISNEW")
    public String getIsnew() {
        return this.isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    @Column(name = "HTMLPATH")
    public String getHtmlpath() {
        return this.htmlpath;
    }

    public void setHtmlpath(String htmlpath) {
        this.htmlpath = htmlpath;
    }

    @Column(name = "PRODUCTSN")
    public String getProductsn() {
        return this.productsn;
    }

    public void setProductsn(String productsn) {
        this.productsn = productsn;
    }

    @Column(name = "GOODSPARAMETERVALUE")
    public String getGoodsparametervalue() {
        return this.goodsparametervalue;
    }

    public void setGoodsparametervalue(String goodsparametervalue) {
        this.goodsparametervalue = goodsparametervalue;
    }

    @Column(name = "FREEZESTORE")
    public Integer getFreezestore() {
        return this.freezestore;
    }

    public void setFreezestore(Integer freezestore) {
        this.freezestore = freezestore;
    }

    @Column(name = "KEYWORDID")
    public String getKeywordid() {
        return this.keywordid;
    }

    public void setKeywordid(String keywordid) {
        this.keywordid = keywordid;
    }

    @Column(name = "UNITNAMEID")
    public String getUnitnameid() {
        return this.unitnameid;
    }

    public void setUnitnameid(String unitnameid) {
        this.unitnameid = unitnameid;
    }

    @Column(name = "GOODSTYPENAME")
    public String getGoodstypename() {
        return this.goodstypename;
    }

    public void setGoodstypename(String goodstypename) {
        this.goodstypename = goodstypename;
    }

    @Column(name = "USERSETNUM")
    public String getUsersetnum() {
        return this.usersetnum;
    }

    public void setUsersetnum(String usersetnum) {
        this.usersetnum = usersetnum;
    }

    @Column(name = "ISSPECIFICATIONSOPEN")
    public String getIsspecificationsopen() {
        return this.isspecificationsopen;
    }

    public void setIsspecificationsopen(String isspecificationsopen) {
        this.isspecificationsopen = isspecificationsopen;
    }

    @Column(name = "TOTALSTAR")
    public Integer getTotalstar() {
        return this.totalstar;
    }

    public void setTotalstar(Integer totalstar) {
        this.totalstar = totalstar;
    }

    @Column(name = "TOTALSTARUSER")
    public Integer getTotalstaruser() {
        return this.totalstaruser;
    }

    public void setTotalstaruser(Integer totalstaruser) {
        this.totalstaruser = totalstaruser;
    }

    @Column(name = "TOTALCOMMENT")
    public Integer getTotalcomment() {
        return this.totalcomment;
    }

    public void setTotalcomment(Integer totalcomment) {
        this.totalcomment = totalcomment;
    }

    @Column(name = "ISVIRTUALSALE")
    public String getIsvirtualsale() {
        return this.isvirtualsale;
    }

    public void setIsvirtualsale(String isvirtualsale) {
        this.isvirtualsale = isvirtualsale;
    }

    @Column(name = "ISMOBILEPLATFORMGOODS")
    public String getIsmobileplatformgoods() {
        return this.ismobileplatformgoods;
    }

    public void setIsmobileplatformgoods(String ismobileplatformgoods) {
        this.ismobileplatformgoods = ismobileplatformgoods;
    }

    @Column(name = "SALES")
    public Integer getSales() {
        return this.sales;
    }

    public void setSales(Integer sales) {
        this.sales = sales;
    }

    @Column(name = "REALSALES")
    public Integer getRealsales() {
        return this.realsales;
    }

    public void setRealsales(Integer realsales) {
        this.realsales = realsales;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATETIME", length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Column(name = "VERSIONT")
    public Integer getVersiont() {
        return this.versiont;
    }

    public void setVersiont(Integer versiont) {
        this.versiont = versiont;
    }

    @Column(name = "COMMODITYLIST")
    public String getCommoditylist() {
        return this.commoditylist;
    }

    public void setCommoditylist(String commoditylist) {
        this.commoditylist = commoditylist;
    }

    @Column(name = "ISOUTSITE")
    public String getIsoutsite() {
        return this.isoutsite;
    }

    public void setIsoutsite(String isoutsite) {
        this.isoutsite = isoutsite;
    }

    @Column(name = "OUTSITELINK")
    public String getOutsitelink() {
        return this.outsitelink;
    }

    public void setOutsitelink(String outsitelink) {
        this.outsitelink = outsitelink;
    }

    @Column(name = "SUBGOODSNAME")
    public String getSubgoodsname() {
        return this.subgoodsname;
    }

    public void setSubgoodsname(String subgoodsname) {
        this.subgoodsname = subgoodsname;
    }

    @Column(name = "SHOPID")
    public String getShopid() {
        return this.shopid;
    }

    public void setShopid(String shopid) {
        this.shopid = shopid;
    }

    @Column(name = "SHOPNAME")
    public String getShopname() {
        return this.shopname;
    }

    public void setShopname(String shopname) {
        this.shopname = shopname;
    }

    @Column(name = "ISGROUP")
    public String getIsgroup() {
        return this.isgroup;
    }

    public void setIsgroup(String isgroup) {
        this.isgroup = isgroup;
    }

    @Column(name = "ISSECONDKILL")
    public String getIssecondkill() {
        return this.issecondkill;
    }

    public void setIssecondkill(String issecondkill) {
        this.issecondkill = issecondkill;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "goodst")
    public Set<Goodsrecipet> getGoodsrecipets() {
        return this.goodsrecipets;
    }

    public void setGoodsrecipets(Set<Goodsrecipet> goodsrecipets) {
        this.goodsrecipets = goodsrecipets;
    }

}
