package com.oneler.entity.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recipet generated by hbm2java
 */
@Entity
@Table(name = "recipet", catalog = "goods")
public class Recipet implements java.io.Serializable {

    private String id;
    private String titile;
    private String description;
    private String neestonename;
    private Date createtime;
    private Date updatetime;
    private String author;
    private String sign;
    private Set<Goodsrecipet> goodsrecipets = new HashSet<Goodsrecipet>(0);

    public Recipet() {
    }

    public Recipet(String id) {
        this.id = id;
    }

    public Recipet(String id, String titile, String description, String neestonename, Date createtime, Date updatetime,
            String author, String sign, Set<Goodsrecipet> goodsrecipets) {
        this.id = id;
        this.titile = titile;
        this.description = description;
        this.neestonename = neestonename;
        this.createtime = createtime;
        this.updatetime = updatetime;
        this.author = author;
        this.sign = sign;
        this.goodsrecipets = goodsrecipets;
    }

    @Id

    @Column(name = "ID", unique = true, nullable = false)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "TITILE")
    public String getTitile() {
        return this.titile;
    }

    public void setTitile(String titile) {
        this.titile = titile;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "NEESTONENAME")
    public String getNeestonename() {
        return this.neestonename;
    }

    public void setNeestonename(String neestonename) {
        this.neestonename = neestonename;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 19)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATETIME", length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Column(name = "AUTHOR")
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "SIGN")
    public String getSign() {
        return this.sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipet")
    public Set<Goodsrecipet> getGoodsrecipets() {
        return this.goodsrecipets;
    }

    public void setGoodsrecipets(Set<Goodsrecipet> goodsrecipets) {
        this.goodsrecipets = goodsrecipets;
    }

}
